language: cpp

sudo: required

os:
  - linux
  - osx

dist: trusty

compiler:
  - gcc
  - clang

matrix:
  exclude:
  - os: osx
    compiler: gcc

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq cmake; fi

before_script:
  - ./configure
  - ./configure

script:
  - cd build
  - make
